name: Build and Test HTML

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Serve HTML for testing
      - name: Start a web server
        uses: peaceiris/actions-http-server@v1
        with:
          port: 8080
          root: ./
      
      # Test the HTML file (Basic)
      - name: Validate HTML
        uses: chuhlomin/html-validator-action@v1
        with:
          file: "index.html"
