name: Build and Test HTML

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Validate the HTML file using an actively maintained action
      - name: Validate HTML
        uses: cyb3r-jak3/html-validator-action@v1.0.0
        with:
          files: |
            index.html

      # Serve HTML using Python's built-in HTTP server
      - name: Start a web server
        run: |
          python3 -m http.server 8080 &
